[package]
name = "zeekit"
version = "0.1.0"
edition = "2021"

[dependencies]
dusk-plonk = "0.10.0"
dusk-jubjub = "0.11.1"
dusk-bytes = "0.1.5"
rand_core = "0.6.3"
lazy_static = "1.4.0"
num-bigint = "0.4"
num-integer = "0.1"
